#!/bin/bash

REGION="XXXXXXXX"
BUCKET_NAME="XXXXXXX"
API_GATEWAY_URL="XXXXXXXXXXXX"


sudo yum update –y
sudo yum install -y httpd24 php56
maxsize=25M
sudo sed -i 's/upload_max_filesize = .*/upload_max_filesize = '${maxsize}'/' /etc/php.ini
sudo service httpd start
sudo chkconfig httpd on
sudo groupadd www
sudo usermod -a -G www ec2-user
sudo su ec2-user
sudo chown -R root:www /var/www
sudo chmod 2775 /var/www
find /var/www -type d -exec sudo chmod 2775 {} +
find /var/www -type f -exec sudo chmod 0664 {} +
cd /var/www/html
wget https://s3.amazonaws.com/awstrainingwavestone/awslab-master.zip
unzip -q awslab-master.zip
mv awslab-master/* .
rm awslab-master.zip
rm -R awslab-master/ install/

sed -i "s/'BUCKET_NAME'/\"$BUCKET_NAME\"/g" /var/www/html/index.php
sed -i "s/'S3_REGION'/\"$REGION\"/g" index.php
sed -i "s,http://amazon-api-gateway-url.com/update-me\!,$API_GATEWAY_URL,g" apigatewayclient.js
